name: Update Prebid Config

on:
  push:
    paths:
      - deployment/ecr/prebid-server/current-config/**

concurrency:
  group: config-deployment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-prebid-config:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-session-token: ${{ secrets.AWS_ACCESS_TOKEN }}


      - name: Upload files
        run: aws s3 cp deployment/ecr/prebid-server/current-config/ ${{vars.AWS_CONFIG_BUCKET_PATH}} --recursive

      - name: Restart ECS Cluster Service
        run: |
          aws ecs update-service \
            --cluster ${{ vars.AWS_ECS_CLUSTER_NAME }} \
            --service ${{ vars.AWS_ECS_SERVICE_NAME }} \
            --force-new-deployment
