name: AWS CDK Deployment

on:
  push:
    branches: 
      - main
      - save

permissions:
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
          aws-session-token: ${{ secrets.AWS_ACCESS_TOKEN }}
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd source
          python -m pip install --upgrade pip
          pip install -r requirements-poetry.txt
          poetry install
          npm install -g aws-cdk


      - name: Run tests
        run: |
          cd deployment
          bash ./run-unit-tests.sh --in-venv 1
      
      - name: Build 
        run: |
          cd source/infrastructure
          cdk bootstrap --cloudformation-execution-policies arn:aws:iam::aws:policy/AdministratorAccess
          cdk synth
      
      - name: Deploy
        run: cdk deploy